---
# handlers file for backup_server
- name: Update CA trust
  become: true
  ansible.builtin.command: update-ca-trust
  changed_when: true

- name: Reload systemd
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
